name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get project
        uses: actions/checkout@v3
      - name: Install c++ and cmake and xvfb and format
        run: |
          sudo apt update -y
          sudo apt install -y cmake build-essential git
          sudo apt-get install -y xvfb
          sudo apt-get install clang-format
      - name: Install gtest
        run: sudo apt-get install libgtest-dev
      - name: Install SFML-2.5.1
        run: |
          wget https://www.sfml-dev.org/files/SFML-2.5.1-linux-gcc-64-bit.tar.gz
          tar -xvf SFML-2.5.1-linux-gcc-64-bit.tar.gz
          mkdir SFML-2.5.1_for_linux
          mv SFML-2.5.1/* SFML-2.5.1_for_linux/
      - name: Format code
        run: find . -name "*.cpp" -o -name "*.h" | xargs clang-format -i
      - name: Push changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global --add safe.directory /github/workspace
          git commit -a -m "Format code"
          git push -u origin checkpoint_4
      - name: Build
        run: |
          mkdir cmake-build-debug
          cd cmake-build-debug
          cmake ..
          make
          cd ..
      - name: Testing
        run: |
          cd exe
          xvfb-run -a ./Test